/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.41
 * Generated at: 2021-01-18 01:41:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bmiProc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>BMI 결과</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

request.setCharacterEncoding("UTF-8");
String csNm = request.getParameter("csNm");
double height = Double.parseDouble(request.getParameter("height"));
double weight = Double.parseDouble(request.getParameter("weight"));

double result=0;

result = weight / Math.pow(height,2);

result = Math.floor(result*10)/10;
if(height > 2.5) {
	result = weight*10000 / Math.pow(height,2);
	result = Math.floor(result*10)/10;
}


String bmiStr = "";
if (result < 18.5) {
	bmiStr = "저체중";
} else if (result <= 23) {
	bmiStr = "정상";
} else if (result <= 25) {
	bmiStr = "경도비만";
} else if (result<= 30) {
	bmiStr = "고도비만";
} else if (30 < result) {
	bmiStr = "초고도비만";
}


      out.write('\r');
      out.write('\n');
      out.print(csNm );
      out.write("님의 키는 ");
      out.print(height );
      out.write(" 몸무게는 ");
      out.print(weight );
      out.write(" 입니다.<p/>\r\n");
      out.write("bmi는 ");
      out.print(result );
      out.write(" 이고, ");
      out.print(bmiStr );
      out.write(" 입니다.<p/><br>\r\n");
      out.write("이런 물건은 어떠신가요?<p/>\r\n");
if(bmiStr.equals("저체중")){ 

      out.write("\r\n");
      out.write("<a href=\"https://adcr.naver.com/adcr?x=mqd9bGLi2Qx6L5pILFN1T////w==k7Wl6jceDjjAsqT/60Vr4xXA17y14c1lQDgVPVku7Yzc7+5dNUvDIP5EUYP4XEFP1SD/NND9QFjsz56XNYS5TDa1GZb4fBnXlk6ylVxyAShXcjpY75Ll2Du8GDvpbO1vQcq7nSp/Gc/wrT+1TMRsoB4L5REGIg15N454GMuS635DbS1DM6f24W8IfAxlb1+RfqVBqItwyLg3nGduAq0UhCbyYo8AvAChLYUYJmpt1CgEui9mbp9+dd0PGCI1XUQfWT1vJmFx4uqHuh9PmfpjDBKOh7K9TUMTMbVvX1ouqNGH6P0T5po0NV9v2cfiCsMpvApUHjTJhFHXQXANKlQh+zXR4vd9AiHtoOmHEjWjYLz1TKkO5UzhyFkaGizgF/MnnuWYJxyywV6f0Q2gJtSq6bt3ABBKXAOWNUb1jsceYd5om3VhAJ0jd9g7+vk4a3IQsSi1tHOhPpjGLYjZmrOYZUCinggrZCZAZLhimMsbXtWZWnAYnDyK1vGYyzlC0ry/NAG12VL0s5v4bl2A/5cVk9vAa73KVGkaqu8WiTO/ehMP8OOBUc4HlGkFjfuB42/Mm6mzHqujnoe1dAtgdgwcfzNRJVxnCp/5tTPFVmTgocq1TKFVobpTb+QDZR5UdQzMwd9pHEo1Xb2RdksDGuyOY7dOTR17/mPPG0ygXQqXkAdN636cu9JbT2XkrRp+F06ZEeau+v1GZoW6iy7ctyOpMefhnZCEJOHjpqzQVi/8HMMODceMnbfIjr7AJfYhfyxiH+m1RTIO9nspOmogZStxGPdj7p4g9I1+JyGKcorbTrTYpyuFZTBK4Klm2KSAm9iG6TpR1t0slmLbdrlanZoZ0hQ==\" target=\"_blank\" class=\"thumbnail_thumb__3Agq6\" rel=\"noopener\" data-nclick=\"N=a:lst*A.image,r:1,i:82466262592\"><img width=\"140\" height=\"140\" alt=\"[BSN] 신타6 엣지 초코맛 단백질보충제 1.82kg X 1통(48회) +간편팩증정\" src=\"https://searchad-phinf.pstatic.net/MjAyMTAxMDRfMjI0/MDAxNjA5NzI0NzgxNjg2.VPGg9SHjqchsfHXTswdoJovh9mihO0WRL1pSITeKUg4g.tH_RtlzhOATyEymU556qwPaSF67P30sEvS7Mom6Sejgg.PNG/1923863-e4e5a662-d487-41de-a9c7-f16e2ba14678.png?type=f200\"></a>\r\n");
} 
      out.write('\r');
      out.write('\n');
if(bmiStr.equals("정상")){ 

      out.write("\r\n");
      out.write("<a href=\"https://cr.shopping.naver.com/adcr.nhn?x=mOxI3tlK3gnh4dPX0O%2B4hf%2F%2F%2Fw%3D%3DsZt7brUkKXXDBwUbqdwUVcp%2FpBBtSG%2BB7hs6Uy8DCB3ef99ETEvSiWmG8P40kbpSxBY%2F5VWCEda8p418Bv4QzEEbAoeRkvpJaJBMwPydFbM8QhkkHXK4%2FmSRy5icYE%2F27m2RfJqLF2Xkw4q4dIcYdA5d2IHYT%2Br4Ks1NxohKUhUuz8kGmHgXzMC1UHb8J4FMDMBbAUTLhEczrfo6o%2BFCYJ9koDZhZTyE2PqJzLGA4wO4TQKSkpMp5naGn6SWlmW4Gjg9UKh74%2FzSpLswi2fMS2c0Fp6fhOJRM8RPnTjq5G3LL%2Fowdnq7%2Fmfq67OVRzok0S5SJNLgIdS1XFCtZ5GETGAnWKNF9y30IZdAPlfpc8ZXlBrESKB%2FAN%2BeyV55nZnAyGtWOzT%2Fs1Q%2BpQfvkcbQokqG2NUEUdWnnR72HtWtxy0dKI194O3yVGRkTAKu5NZTn37xLGIzVnLruO2FdV%2FooFmrebY42GXIkUNBp5dyDg45z8fQE6UcocYdsKIORLNRzp%2BYV%2Ff1IV85CSIaXlXbAB30nwdVWVWgH2wNpALuMmZLzXvyeKIgiGg3O%2FR7bGWOvcTAJresIH7woseesF1SfuOYQsU7TtARBhTKL6TvT1FMfiiMSrMfwKLClRDlm8b9banWwDoShe6maJRTaS2ME1mToUtM4AK5oWmKbAJ6T3JOFbDf4gHI5rSMJU1BWcIOg&amp;nvMid=11927356299&amp;catId=50002425\" target=\"_blank\" class=\"thumbnail_thumb__3Agq6\" rel=\"noopener\" data-nclick=\"N=a:lst*N.image,r:2,i:11927356299\"><img width=\"140\" height=\"140\" alt=\"센트룸 포맨 포우먼 실버/남성/멀티 코스트코 종합비타민\" src=\"https://shopping-phinf.pstatic.net/main_1192735/11927356299.1.jpg?type=f140\"></a>\r\n");
} 
      out.write('\r');
      out.write('\n');
if(bmiStr.equals("경도비만")){ 

      out.write("\r\n");
      out.write("<a href=\"https://cr.shopping.naver.com/adcr.nhn?x=yNzZlEmrFCSLZmc2GxHIjP%2F%2F%2Fw%3D%3DsD8ucBFKP1Dncx9qpUELExlr09Ux2zr%2FU3EyRKt6zsfFzZ9gYmXUTYvz%2FMY5qJkIdEHMGWU2QNgWBADh62fNG43g84b46EFc%2BAkNjHGT%2BoabaH%2Bo1uYx3c%2F20TmNqYJspJbscX5utCfc%2FK52VI76k1pdzS7dFF4NlGlGtUsRi6wyKtQ%2FzIb93DqGKflHYX7DmMUr4xqr%2F52%2Bdo85SzQg5uwY7th%2Fb5X%2Fu%2F1YFVAUnhxaK4j5MTwF45Ni1%2FMJqrSg0sfViem1l2ZXIstQzQHgHYrEvVNceRSxPTPVsFrjP3QaqBjqt2lc6BAnF2r13bTw%2FVV3pn6Znl%2B9MAtsEE%2BZ8ouacYsA2T1ONC2M4R1%2F3Eb%2F9gaSlTqjRTdjbxTKaRSTCRJ%2BOzA3kE6rs7uekGLll4xO65AueXJZCN2mHf%2FhUTVly3tldpZcdYNEsGxNW%2BphEzfNVo1KcSVSazeZg7M%2BAaarWdnF1eS7yqupbBGhpGNXGOrmiPr3ujlpq2qFyZMiw0e%2FWS34dJqnVsr3adi3coUAIMaNrRxMpGd0cx1WF4Q%2FpIUaHu7aXpEo3zuBKxwvisYOkWFDoEUv4Ux%2BW01vhbduZ0Q6F70c0hxiD%2F2B0gZkE8Ud1cXBGA5S916T%2FxuEgXfV9GX3DHGFqof86DEpn1Pqo3V%2B6p3aafJnxZqnu3Pq2XJPHqy6v4o9aCwOVagPkn14m5RMtm4%2BrOmzHR0X9t7FDxektjKNxuEs%2Bb5dBXT3Njqh%2FZemCCOboDhnweAmG&amp;nvMid=81803829035&amp;catId=50001767\" target=\"_blank\" class=\"thumbnail_thumb__3Agq6\" rel=\"noopener\" data-nclick=\"N=a:lst*N.image,r:2,i:81803829035\"><img width=\"140\" height=\"140\" alt=\"다이어트쉐이크 맛있는 단백질쉐이크 보조제 단기간 5일 식사대용 음식 단기 FMD 식단\" src=\"https://shopping-phinf.pstatic.net/main_8180382/81803829035.6.jpg?type=f140\"></a>\r\n");
} 
      out.write('\r');
      out.write('\n');
if(bmiStr.equals("고도비만")){ 

      out.write("\r\n");
      out.write("<a href=\"https://cr.shopping.naver.com/adcr.nhn?x=yNzZlEmrFCSLZmc2GxHIjP%2F%2F%2Fw%3D%3DsD8ucBFKP1Dncx9qpUELExlr09Ux2zr%2FU3EyRKt6zsfFzZ9gYmXUTYvz%2FMY5qJkIdEHMGWU2QNgWBADh62fNG43g84b46EFc%2BAkNjHGT%2BoabaH%2Bo1uYx3c%2F20TmNqYJspJbscX5utCfc%2FK52VI76k1pdzS7dFF4NlGlGtUsRi6wyKtQ%2FzIb93DqGKflHYX7DmMUr4xqr%2F52%2Bdo85SzQg5uwY7th%2Fb5X%2Fu%2F1YFVAUnhxaK4j5MTwF45Ni1%2FMJqrSg0sfViem1l2ZXIstQzQHgHYrEvVNceRSxPTPVsFrjP3QaqBjqt2lc6BAnF2r13bTw%2FVV3pn6Znl%2B9MAtsEE%2BZ8ouacYsA2T1ONC2M4R1%2F3Eb%2F9gaSlTqjRTdjbxTKaRSTCRJ%2BOzA3kE6rs7uekGLll4xO65AueXJZCN2mHf%2FhUTVly3tldpZcdYNEsGxNW%2BphEzfNVo1KcSVSazeZg7M%2BAaarWdnF1eS7yqupbBGhpGNXGOrmiPr3ujlpq2qFyZMiw0e%2FWS34dJqnVsr3adi3coUAIMaNrRxMpGd0cx1WF4Q%2FpIUaHu7aXpEo3zuBKxwvisYOkWFDoEUv4Ux%2BW01vhbduZ0Q6F70c0hxiD%2F2B0gZkE8Ud1cXBGA5S916T%2FxuEgXfV9GX3DHGFqof86DEpn1Pqo3V%2B6p3aafJnxZqnu3Pq2XJPHqy6v4o9aCwOVagPkn14m5RMtm4%2BrOmzHR0X9t7FDxektjKNxuEs%2Bb5dBXT3Njqh%2FZemCCOboDhnweAmG&amp;nvMid=81803829035&amp;catId=50001767\" target=\"_blank\" class=\"thumbnail_thumb__3Agq6\" rel=\"noopener\" data-nclick=\"N=a:lst*N.image,r:2,i:81803829035\"><img width=\"140\" height=\"140\" alt=\"다이어트쉐이크 맛있는 단백질쉐이크 보조제 단기간 5일 식사대용 음식 단기 FMD 식단\" src=\"https://shopping-phinf.pstatic.net/main_8180382/81803829035.6.jpg?type=f140\"></a>\r\n");
} 
      out.write('\r');
      out.write('\n');
if(bmiStr.equals("초고도비만")){ 

      out.write("\r\n");
      out.write("<a href=\"https://cr.shopping.naver.com/adcr.nhn?x=yNzZlEmrFCSLZmc2GxHIjP%2F%2F%2Fw%3D%3DsD8ucBFKP1Dncx9qpUELExlr09Ux2zr%2FU3EyRKt6zsfFzZ9gYmXUTYvz%2FMY5qJkIdEHMGWU2QNgWBADh62fNG43g84b46EFc%2BAkNjHGT%2BoabaH%2Bo1uYx3c%2F20TmNqYJspJbscX5utCfc%2FK52VI76k1pdzS7dFF4NlGlGtUsRi6wyKtQ%2FzIb93DqGKflHYX7DmMUr4xqr%2F52%2Bdo85SzQg5uwY7th%2Fb5X%2Fu%2F1YFVAUnhxaK4j5MTwF45Ni1%2FMJqrSg0sfViem1l2ZXIstQzQHgHYrEvVNceRSxPTPVsFrjP3QaqBjqt2lc6BAnF2r13bTw%2FVV3pn6Znl%2B9MAtsEE%2BZ8ouacYsA2T1ONC2M4R1%2F3Eb%2F9gaSlTqjRTdjbxTKaRSTCRJ%2BOzA3kE6rs7uekGLll4xO65AueXJZCN2mHf%2FhUTVly3tldpZcdYNEsGxNW%2BphEzfNVo1KcSVSazeZg7M%2BAaarWdnF1eS7yqupbBGhpGNXGOrmiPr3ujlpq2qFyZMiw0e%2FWS34dJqnVsr3adi3coUAIMaNrRxMpGd0cx1WF4Q%2FpIUaHu7aXpEo3zuBKxwvisYOkWFDoEUv4Ux%2BW01vhbduZ0Q6F70c0hxiD%2F2B0gZkE8Ud1cXBGA5S916T%2FxuEgXfV9GX3DHGFqof86DEpn1Pqo3V%2B6p3aafJnxZqnu3Pq2XJPHqy6v4o9aCwOVagPkn14m5RMtm4%2BrOmzHR0X9t7FDxektjKNxuEs%2Bb5dBXT3Njqh%2FZemCCOboDhnweAmG&amp;nvMid=81803829035&amp;catId=50001767\" target=\"_blank\" class=\"thumbnail_thumb__3Agq6\" rel=\"noopener\" data-nclick=\"N=a:lst*N.image,r:2,i:81803829035\"><img width=\"140\" height=\"140\" alt=\"다이어트쉐이크 맛있는 단백질쉐이크 보조제 단기간 5일 식사대용 음식 단기 FMD 식단\" src=\"https://shopping-phinf.pstatic.net/main_8180382/81803829035.6.jpg?type=f140\"></a>\r\n");
} 
      out.write("<p/>\r\n");
      out.write("<a href=\"/views/bmi.jsp\"> 다시하기 </a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
